In [40]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [51]:
df = pd.read_csv("/content/drive/MyDrive/sales_dataset.csv")
df.head()

  Salesperson  Product Region        Date  Item Unit  No. of Items  Total Sales
0       Diana  Monitor   East  2023-03-26     768.44            11      8452.84
1       Alice   Laptop   East  2023-01-28     138.38            20      2767.60
2       Alice   Laptop  South  2023-04-30     876.50             1       876.50
3         Bob  Monitor   West  2023-01-08     410.97             3      1232.91
4      Carlos   Mobile  South  2023-01-01    1221.02            14     17094.28

In [52]:
df['Date'] = pd.to_datetime(df['Date'])

df['month'] = df['Date'].dt.month
df

   Salesperson  Product Region  ... No. of Items  Total Sales  month
0        Diana  Monitor   East  ...           11      8452.84      3
1        Alice   Laptop   East  ...           20      2767.60      1
2        Alice   Laptop  South  ...            1       876.50      4
3          Bob  Monitor   West  ...            3      1232.91      1
4       Carlos   Mobile  South  ...           14     17094.28      1
..         ...      ...    ...  ...          ...          ...    ...
95       Alice  Monitor  South  ...           13     14284.01      5
96         Bob   Tablet   West  ...           19      7463.58      4
97      Carlos  Monitor   West  ...            2      2868.38      4
98       Diana   Mobile  North  ...            8      1868.40      4
99        Esha   Tablet   West  ...            7      4161.57      5

[100 rows x 8 columns]

In [53]:
df.drop('Date', axis=1, inplace = True)
df

   Salesperson  Product Region  Item Unit  No. of Items  Total Sales  month
0        Diana  Monitor   East     768.44            11      8452.84      3
1        Alice   Laptop   East     138.38            20      2767.60      1
2        Alice   Laptop  South     876.50             1       876.50      4
3          Bob  Monitor   West     410.97             3      1232.91      1
4       Carlos   Mobile  South    1221.02            14     17094.28      1
..         ...      ...    ...        ...           ...          ...    ...
95       Alice  Monitor  South    1098.77            13     14284.01      5
96         Bob   Tablet   West     392.82            19      7463.58      4
97      Carlos  Monitor   West    1434.19             2      2868.38      4
98       Diana   Mobile  North     233.55             8      1868.40      4
99        Esha   Tablet   West     594.51             7      4161.57      5

[100 rows x 7 columns]

In [54]:
X = df.drop("Total Sales", axis = 1)
y = df["Total Sales"]
print(X)
print(y)

   Salesperson  Product Region  Item Unit  No. of Items  month
0        Diana  Monitor   East     768.44            11      3
1        Alice   Laptop   East     138.38            20      1
2        Alice   Laptop  South     876.50             1      4
3          Bob  Monitor   West     410.97             3      1
4       Carlos   Mobile  South    1221.02            14      1
..         ...      ...    ...        ...           ...    ...
95       Alice  Monitor  South    1098.77            13      5
96         Bob   Tablet   West     392.82            19      4
97      Carlos  Monitor   West    1434.19             2      4
98       Diana   Mobile  North     233.55             8      4
99        Esha   Tablet   West     594.51             7      5

[100 rows x 6 columns]
0      8452.84
1      2767.60
2       876.50
3      1232.91
4     17094.28
        ...
95    14284.01
96     7463.58
97     2868.38
98     1868.40
99     4161.57
Name: Total Sales, Length: 100, dtype: float64

In [55]:
categorical_features = ["Salesperson", "Product", "Region"]
numeric_features = ["Item Unit", "No. of Items", "month"]

In [56]:
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ],
    remainder='passthrough'
)

In [57]:
pipeline = Pipeline([
    ('preprocess', preprocessor),
    ('model', LinearRegression())
])

In [58]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
pipeline.fit(X_train, y_train)

In [63]:
y_pred = pipeline.predict(X_test)

In [65]:
print("R² Score:", r2_score(y_test, y_pred))
print("MSE:", (mean_squared_error(y_test, y_pred)))
print("MAE", (mean_absolute_error(y_test, y_pred)))

R² Score: 0.8690319776297711
MSE: 6601040.719355542
MAE 1818.7018098177855

In [73]:
new_data = pd.DataFrame({
    "Salesperson" : ["Alice"],
    "Product" : ["Laptop"],
    "Region" : ["South"],
    "Item Unit" : [1300],
    "No. of Items" : [10],
    "month" : [10]

})
new_data

  Salesperson Product Region  Item Unit  No. of Items  month
0       Alice  Laptop  South       1300            10     10

In [74]:
new_pred = pipeline.predict(new_data)
print("The predicted sales is:",new_pred[0])

The predicted sales is: 13747.565028571225